{% set version = "0.6-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgeos
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/rgeos_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rgeos/rgeos_{{ version }}.tar.gz
  sha256: 420dbd48c0e8c840686b6ed29384715723d6926a1f9b0c437c60ad1853eef7f2
  patches:
    - patches/001-skip-svnversion.patch

build:
  number: 0
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-sp                         # [build_platform != target_platform]
    - autoconf                     # [unix]
    - posix                        # [win]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-sp >=1.1_0
    - geos
  run:
    - r-base
    - geos
    - r-sp >=1.1_0

test:
  commands:
    - R -e "library('rgeos')"  # [not win]
    - R -e \"library('rgeos')\"  # [win]

about:
  home: https://r-forge.r-project.org/projects/rgeos/
  doc_url: http://rgeos.r-forge.r-project.org/index.html
  license: GPL-2.0-or-later
  summary: Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology operations on geometries. The 'GEOS' library is external to the package, and, when installing the package from source, must be correctly installed first. Windows and Mac Intel OS X binaries are provided on 'CRAN'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
