{% set version = "0.5-9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgeos
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/rgeos_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rgeos/rgeos_{{ version }}.tar.gz
  sha256: ab90cbfe6a3680a9d2eed5e655064a075adc66788e304468969ab7cc2df0e3d4

build:
  number: 1
  merge_build_host: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix  # [win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-sp >=1.1_0
    - geos

  run:
    - r-base
    - geos
    - r-sp >=1.1_0

test:
  commands:
    - R -e "library('rgeos')"  # [not win]
    - R -e \"library('rgeos')\"  # [win]

about:
  home: https://r-forge.r-project.org/projects/rgeos/
  license: GPL-2.0-or-later
  summary: Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology operations on geometries. The 'GEOS' library is external to the package, and, when installing the package from source, must be correctly installed first. Windows and Mac Intel OS X binaries are provided on 'CRAN'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
