{% set version = "0.3-28" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgeos
  version: {{ version|replace("-", "_") }}

source:
  fn: rgeos_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rgeos_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rgeos/rgeos_{{ version }}.tar.gz
  sha256: 18e068dc68cf4da9f88aa42125edbd54bfce3c23101f994068ef91571cbccbb5
  patches:
    - fix_libs.patch

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-sp >=1.1_0
    - geos

  run:
    - r-base
    - geos
    - r-sp >=1.1_0

test:
  commands:
    - $R -e "library('rgeos')"  # [not win]
    - "\"%R%\" -e \"library('rgeos')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/rgeos/
  license: GPL (>= 2)
  summary: Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology
    operations on geometries. The 'GEOS' library is external to the package, and, when
    installing the package from source, must be correctly installed first. Windows and
    Mac Intel OS X binaries are provided on 'CRAN'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
