{% set version = '0.4-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgeos
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rgeos_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rgeos/rgeos_{{ version }}.tar.gz
  sha256: 1e86ec8afc157f2d0d4fa61213b63667aef22a4527f30cbd6d6ccf89780de0a7

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-sp >=1.1_0
    - geos
  run:
    - r-base
    - geos
    - {{native}}gcc-libs         # [win]
    - r-sp >=1.1_0

test:
  commands:
    - $R -e "library('rgeos')"           # [not win]
    - "\"%R%\" -e \"library('rgeos')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/rgeos/ http://trac.osgeo.org/geos/
  license: GPL (>= 2)
  summary: Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology
    operations on geometries. The 'GEOS' library is external to the package, and, when
    installing the package from source, must be correctly installed first. Windows and
    Mac Intel OS X binaries are provided on 'CRAN'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rgeos
# Title: Interface to Geometry Engine - Open Source ('GEOS')
# Version: 0.4-3
# Date: 2019-04-23
# Depends: R (>= 3.3.0), methods, sp (>= 1.1-0)
# Imports: utils, stats, graphics
# LinkingTo: sp
# Suggests: maptools (>= 0.8-5), testthat, XML, maps, rgdal
# NeedsCompilation: yes
# LazyLoad: yes
# Description: Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology operations on geometries. The 'GEOS' library is external to the package, and, when installing the package from source, must be correctly installed first. Windows and Mac Intel OS X binaries are provided on 'CRAN'.
# Authors@R: c( person("Roger", "Bivand", role = c("cre", "aut"), email = "Roger.Bivand@nhh.no", comment=c(ORCID="0000-0003-2392-6140")), person("Colin", "Rundel", role = "aut"), person("Edzer", "Pebesma", role = "ctb"), person("Rainer", "Stuetz", role = "ctb"), person("Karl Ove", "Hufthammer", role = "ctb"), person("Patrick", "Giraudoux", role = "ctb"), person("Martin", "Davis", role = c("cph", "ctb")), person("Sandro", "Santilli", role = c("cph", "ctb")))
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/rgeos/ http://trac.osgeo.org/geos/
# SystemRequirements: GEOS (>= 3.2.0); for building from source: GEOS from http://trac.osgeo.org/geos/; GEOS OSX frameworks built by William Kyngesburye at http://www.kyngchaos.com/ may be used for source installs on OSX.
# RoxygenNote: 6.1.1
# Packaged: 2019-04-24 09:18:17 UTC; rsb
# Author: Roger Bivand [cre, aut] (<https://orcid.org/0000-0003-2392-6140>), Colin Rundel [aut], Edzer Pebesma [ctb], Rainer Stuetz [ctb], Karl Ove Hufthammer [ctb], Patrick Giraudoux [ctb], Martin Davis [cph, ctb], Sandro Santilli [cph, ctb]
# Maintainer: Roger Bivand <Roger.Bivand@nhh.no>
# Repository: CRAN
# Date/Publication: 2019-04-24 10:00:03 UTC
