travis:
  secure:
    BINSTAR_TOKEN: iPo2DUUhOqIj/vUFo3xyHMnpzKBkH6RNpxug42/kgPiU0cYwpAQ1n1P85CKTMh0SN2g+ydLb2s38o6AArue+2TRrSicCuGan+Z48FDmHeqPbqpfcLvQoTOcw7P+gl5/i8n6w8My8W4Vn6c8xDdYdYpuhSX8BZlCe5d+YwIQJFmwKob3G6jEvxF2ZdCIGMeEqYfEt4v/0/QXJmyOYMQXBT5fKGne4ZsGOpqtrCfwh5J7wMuUqOGc1pM4G/vgWFAFNCGGd7VRcELSxS4Pk+aPQzHCB6mTmRhxHk3ksjnNEl89lwbxmidybtVekA9j43a6J8qZGowKhhMEzxdTHO0R38f/gXywLVOo1I6oAITXg8HK6blJZCkG0OSNsiuA7DXwAXSnts1RLgR9GBUTPTAr8ntf4SxrCO729zft7z3NJcyHFGnmTZXeVxgD6JZ14OmYOZLzsW4vuf/ZJWJ2/0BynDBNqhnQrobgum49Jjml+1NJeK7yFtJHlzNLNgl5FgJMbuZQmHqf/dHA+iPJMgUHeACEDet6baSEQeQ496XK0KGXxo2feiL+K7y7nrzmSBUX0aUJVrLOQkPePgccYTSG7IlYaoJjR0BYOpvxu5IxvKEJLTyGiSmedXvn8l4mgKvJ9zb2qUWf5DzTnqrYzWNuKfzU8NEg8dnuygEevzc+uuUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
