appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LVv63VMkwH6NvyotHBFnhXkhi+DIN5c0tPJCjka65lFzzhbVJ7ht6kZvKFKcKPSHTPJyyVRfTDgABENwSn0OwY7LzrwDNWxnGajhRSFh54Z9L5tvfVCdpACGxM5LIIiBp0STng2Qz8q/y1+omTWTJL0bYs7fRSxn1jc8qsbWVQnypZL9ZnqXUrKV07uhO3QnXXH6zmZeUm1MklYBybjAEYIQGqlz1Cj9n8SnagBx0sPxGd5p5GZ4Am6MIjDdlz/AZKN6W8O0IVYnaYW4SCZg1L8QFSYXgNfeVFxGhNOQfuYVy83HKsZv8rr14d7HNzblNQ4gZ2TCUKHl+PHDo/IBfNA69SGLo9iNCTNQ5xzPPL4vrpF51+a9Hhtd037DRwfe5voV+XJHAKtH3DZ5AsBLRHbVeODuLltvscebBMCQnVaYsHmRDfDkG8K1xFB4vZnUI1Jz6Cjw69VvW4Ipap4YzCHEy8ebPKvV1JPqH82USlMfaR+X+s+TDdhnNlSQirvqNNYHb9/IlsEnlywc0v270xh1nOQU6MfdsSM/z9v3yxbpx5l62j88BhK5U0rVPeg2bzMMP1kKHYhSHYHudDHKHsI3wlp2tpFfQ3/vq/lR75G6B8d8PX9+LZd1PDZbzqDalb1uCalJkwglJ9uxJKXVB/GieVrHuSoq1cLDMCgKLL0=
conda_forge_output_validation: false
